# platform :ios, '9.0'
target 'AwesomeProject' do
  # Pods for ReactNativeMaps
  pod 'GoogleMaps'
    pod 'react-native-maps', :path => '../node_modules/react-native-maps'

    pod 'ReactNativeNavigation', :path => '../node_modules/react-native-navigation'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  end